version: "3.8"

services:
  php:
    container_name: acmrr-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    container_name: acmrr-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: acmrr
      MYSQL_USER: acmrr
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - acmrr_db:/var/lib/mysql

  nginx:
    container_name: acmrr-nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  acmrr_db:
